#
#  .circleci/config.yml
#  Blockchain
#
#  Created by Maurice A. on 10/1/18.
#  Copyright © 2018 Blockchain Luxembourg S.A. All rights reserved.
#
#  CircleCI
#  --------
#  ‣ Run commands are executed using non-login shells by default, so you must explicitly source any dotfiles as part of the command.
#    It’s possible to specify a multi-line command, each line of which will be run in the same shell.
#
#  ‣ It is currently not possible to delete the cache in CircleCI 2.0
#    Workaround: rename the cache key to force generation of a new cache.
#
#  ‣ Environment variables (e.g. API keys) are defined in the project settings on circleci.com.
#
#  ‣ Your project’s default branch will never auto cancel builds. This feature only applies to non-workflow builds,
#    builds triggered by pushes to GitHub, or workflow builds that use the new build processing feature.
#
#  ‣ Workflows will ignore job-level branching. If you use job-level branching and later add workflows,
#    you must remove the branching at the job level and instead declare it in the workflows section.
#
#  ‣ Builds without workflows require a build job.
#
#  ‣ Append `[ci skip]` to your commit message if you don't want to trigger CI for a given commit.
#
#  Fastlane
#  --------
#  ‣ The `setup_circle_ci` Fastlane action must be in the before_all block to perform the following actions:
#    - Create a new temporary keychain for use with Fastlane Match (see the code signing section for more details).
#    - Switch Fastlane Match to readonly mode to make sure CI does not create new code signing certificates or provisioning profiles.
#    - Set up log and test result paths to be easily collectible.
#
#  Cocoapods
#  ---------
#  ‣ Data persisted as a result of running `pod install`:
#    - Blockchain.xcworkspace
#    - Podfile
#    - Podfile.lock
#    - Pods/
#
#  ‣ The Cocoapods master repository is fetched via the CircleCI mirror for better performance.
#
#  ‣ Cocoapods is not specified in the Gemfile because it already comes bundled with the software container.
#    Developers must install it locally using `sudo gem install cocoapods`.
#
#  Ruby Gems
#  ---------
#  ‣ Running `gem env` will show the installation directory of binaries.
#
defaults: &defaults
  working_directory: /Users/distiller/project
  macos:
    xcode: "11.0.0"
  shell: /bin/bash --login -o pipefail
# +------+
# | Jobs |
# +------+
version: 2
jobs:
  # Setup Git Repository
  setup_repo:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - ./
  # Install Dependencies
  # - Install node and npm.
  # - Initialize git submodules.
  # - Buid JavaScript source files.
  # - Install Ruby gems.
  # - Get Firebase config from private repo.
  install_deps:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - restore_cache:
          keys:
            - node-cache-{{ .Environment.NODE_VERSION }}
      - run:
          name: Install Node
          command: |
            cd ~
            git clone https://github.com/creationix/nvm.git .nvm
            cd .nvm && git checkout v0.33.11 && . nvm.sh
            nvm install $NODE_VERSION && nvm use $NODE_VERSION
            if [[ $(npm -v | grep -v "5.6.0") ]]; then
              npm install -g npm@5.6.0
            fi
      - save_cache:
          key: node-cache-{{ .Environment.NODE_VERSION }}
          paths:
            - ~/.nvm
            - /usr/local/lib/node_modules
      - run:
          name: Initialize Submodules
          command: git submodule update --init
      - run:
          name: Update Fastlane
          command: bundle update fastlane
      - run:
          name: Build JavaScript
          command: |
            . ~/.nvm/nvm.sh
            sh scripts/install-js.sh
            sh scripts/build-js.sh
      - restore_cache:
          keys:
            - gems-cache-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install Ruby Gems
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            gem env
            sudo gem cleanup
            sudo gem update bundler
            sudo gem install bundler
            bundle install --path vendor/bundle
            bundle clean
      - save_cache:
          key: gems-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Config Firebase
          command: |
            git clone -b firebase $CREDENTIALS_REPO /tmp/credentials
            mv /tmp/credentials/Firebase /Users/distiller/project/Blockchain/Firebase
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - ./
  # Build OpenSSL library
  build_openssl:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - restore_cache:
          keys:
            - openssl-cache-{{ .Environment.TARGET_IOS_SDK_VERSION }}
      - run:
          name: Build OpenSSL
          command: |
            if [ ! -d "./Submodules/OpenSSL-for-iPhone/bin" ]; then
              cd Submodules/OpenSSL-for-iPhone
              sh build-libssl.sh --cleanup
            fi
      - save_cache:
          key: openssl-cache-{{ .Environment.TARGET_IOS_SDK_VERSION }}
          paths:
            - ~/project/Submodules/OpenSSL-for-iPhone
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - ./Submodules/OpenSSL-for-iPhone
  # Install Pods
  # - Install from cache (if possible).
  # - Append build settings to .xcconfig files.
  install_pods:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - restore_cache:
          keys:
            - pods-{{ checksum "Podfile.lock" }}
      - run:
          name: Install brew dependencies
          command: brew reinstall -s libtool gnu-sed
      - run:
          name: Install Pods
          command: |
            bundle exec pod install --verbose
            git clone -b xcconfig-ci $CREDENTIALS_REPO /tmp/xcconfig
            mkdir Config
            cp /tmp/xcconfig/Config/Development.xcconfig Config/Development.xcconfig
            cp /tmp/xcconfig/Config/Production.xcconfig Config/Production.xcconfig
            cp /tmp/xcconfig/Config/Release.xcconfig Config/Release.xcconfig
            cp /tmp/xcconfig/Config/Staging.xcconfig Config/Staging.xcconfig
      - save_cache:
          key: pods-{{ checksum "Podfile.lock" }}
          paths:
            - ~/.cocoapods
            - ~/Library/Caches/CocoaPods
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - ./Config
            - ./Pods
            - ./Blockchain.xcworkspace
  # Run tests job:
  # - Run unit tests and notify Slack channel.
  run_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Fastlane
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
            bundle exec fastlane scan
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan
  # Archive and export application (staging):
  # - Update code signing.
  # - Get export options plist file from private repo.
  # - Archive the application.
  # - Export the .ipa file.
  archive_and_export_staging_app_store:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Archive & Export Application
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export CREDENTIALS_REPO=$CREDENTIALS_REPO
            export FASTLANE_USER=$FASTLANE_USER
            bundle exec fastlane code_signing
            security find-identity -v -p codesigning
            git clone -b xcodebuild $CREDENTIALS_REPO /tmp/xcodebuild
            xcodebuild -workspace Blockchain.xcworkspace -scheme Blockchain\ \(Staging\) -sdk iphoneos -configuration Release\ Staging archive -archivePath ./output/Blockchain.xcarchive | xcpretty
            xcodebuild -exportArchive -archivePath output/Blockchain.xcarchive -exportOptionsPlist /tmp/xcodebuild/exportOptions.plist -exportPath ./output | xcpretty
      - run:
          name: zip dSYM file
          command: |
            cd ./output/Blockchain.xcarchive/dSYMs
            zip -r /Users/distiller/project/output/Blockchain.app.dSYM.zip Blockchain.app.dSYM
            rm -fr ./output/Blockchain.xcarchive
      - run:
          name: Upload dSYM to Firebase
          command: bundle exec fastlane upload_dsyms
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - output
      - store_artifacts:
          path: output
  archive_and_export_staging_ad_hoc:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Archive & Export Application
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export CREDENTIALS_REPO=$CREDENTIALS_REPO
            export FASTLANE_USER=$FASTLANE_USER
            bundle exec fastlane code_signing
            security find-identity -v -p codesigning
            git clone -b xcodebuild $CREDENTIALS_REPO /tmp/xcodebuild
            xcodebuild -workspace Blockchain.xcworkspace -scheme Blockchain\ \(Staging\) -sdk iphoneos -configuration Release\ Staging archive -archivePath ./output/Blockchain.xcarchive | xcpretty
            xcodebuild -exportArchive -archivePath output/Blockchain.xcarchive -exportOptionsPlist /tmp/xcodebuild/exportOptionsAdHoc.plist -exportPath ./output | xcpretty
            touch ./output/ReleaseNotes.txt | echo "Staging build" >> ./output/ReleaseNotes.txt
      - run:
          name: zip dSYM file
          command: |
            cd ./output/Blockchain.xcarchive/dSYMs
            zip -r /Users/distiller/project/output/Blockchain.app.dSYM.zip Blockchain.app.dSYM
            rm -fr ./output/Blockchain.xcarchive
      - run:
          name: Upload dSYM to Firebase
          command: bundle exec fastlane upload_dsyms
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - output
      - store_artifacts:
          path: output
  # Archive and export application (production):
  # - Update code signing.
  # - Get export options plist file from private repo.
  # - Archive the application.
  # - Export the .ipa file.
  archive_and_export_production_app_store:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Archive & Export Application
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export CREDENTIALS_REPO=$CREDENTIALS_REPO
            export FASTLANE_USER=$FASTLANE_USER
            bundle exec fastlane code_signing
            security find-identity -v -p codesigning
            git clone -b xcodebuild $CREDENTIALS_REPO /tmp/xcodebuild
            xcodebuild -workspace Blockchain.xcworkspace -scheme Blockchain -sdk iphoneos -configuration Release archive -archivePath ./output/Blockchain.xcarchive | xcpretty
            xcodebuild -exportArchive -archivePath output/Blockchain.xcarchive -exportOptionsPlist /tmp/xcodebuild/exportOptions.plist -exportPath ./output | xcpretty
      - run:
          name: zip dSYM file
          command: |
            cd ./output/Blockchain.xcarchive/dSYMs
            zip -r /Users/distiller/project/output/Blockchain.app.dSYM.zip Blockchain.app.dSYM
            rm -fr ./output/Blockchain.xcarchive
      - run:
          name: Upload dSYM to Firebase
          command: bundle exec fastlane upload_dsyms
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - output
      - store_artifacts:
          path: output
  archive_and_export_production_ad_hoc:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Archive & Export Application
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export CREDENTIALS_REPO=$CREDENTIALS_REPO
            export FASTLANE_USER=$FASTLANE_USER
            bundle exec fastlane code_signing
            security find-identity -v -p codesigning
            git clone -b xcodebuild $CREDENTIALS_REPO /tmp/xcodebuild
            xcodebuild -workspace Blockchain.xcworkspace -scheme Blockchain -sdk iphoneos -configuration Release archive -archivePath ./output/Blockchain.xcarchive | xcpretty
            xcodebuild -exportArchive -archivePath output/Blockchain.xcarchive -exportOptionsPlist /tmp/xcodebuild/exportOptionsAdHoc.plist -exportPath ./output | xcpretty
            touch ./output/ReleaseNotes.txt | echo "Production build" >> ./output/ReleaseNotes.txt
      - run:
          name: zip dSYM file
          command: |
            cd ./output/Blockchain.xcarchive/dSYMs
            zip -r /Users/distiller/project/output/Blockchain.app.dSYM.zip Blockchain.app.dSYM
            rm -fr ./output/Blockchain.xcarchive
      - run:
          name: Upload dSYM to Firebase
          command: bundle exec fastlane upload_dsyms
      - persist_to_workspace:
          root: /Users/distiller/project
          paths:
            - output
      - store_artifacts:
          path: output
  upload_app_center_staging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Setup keychain
          command: |
            security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
            # Disable keychain locking timeout
            security set-keychain-settings $KEYCHAIN_NAME
            security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
            security default-keychain -s $KEYCHAIN_NAME
      - run:
          name: Install App Center
          command: npm install -g appcenter-cli
      - run:
          name: Distribute IPA
          command: |
            appcenter telemetry off --disable-telemetry
            appcenter login --token $APP_CENTER_API_TOKEN --quiet
            appcenter distribute release -f ./output/Blockchain.ipa -g Testers --app $APP_CENTER_APP --release-notes-file ./output/ReleaseNotes.txt --quiet
  upload_app_center_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Setup keychain
          command: |
            security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
            # Disable keychain locking timeout
            security set-keychain-settings $KEYCHAIN_NAME
            security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
            security default-keychain -s $KEYCHAIN_NAME
      - run:
          name: Install App Center
          command: npm install -g appcenter-cli
      - run:
          name: Distribute IPA
          command: |
            appcenter telemetry off --disable-telemetry
            appcenter login --token $APP_CENTER_API_TOKEN --quiet
            appcenter distribute release -f ./output/Blockchain.ipa -g Testers --app $APP_CENTER_PRODUCTION_APP --release-notes-file ./output/ReleaseNotes.txt --quiet
  upload_app_store:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /Users/distiller/project
      - run:
          name: Upload to App Store Connect
          command: |
            export LANG=en_US.UTF-8
            export LC_ALL=en_US.UTF-8
            export CREDENTIALS_REPO=$CREDENTIALS_REPO
            export FASTLANE_USER=$FASTLANE_USER
            bundle exec fastlane upload
# +-----------+
# | Workflows |
# +-----------+
workflows:
  version: 2
  run-tests-only:
    jobs:
      - setup_repo:
          filters:
            branches:
              ignore: release
      - install_deps:
          requires:
            - setup_repo
      - build_openssl:
          requires:
            - install_deps
      - install_pods:
          requires:
            - setup_repo
            - install_deps
      - run_tests:
          requires:
            - install_deps
            - build_openssl
            - install_pods
